{% set version = "1.0.1" %}

package:
  name: js-regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/js-regex/js-regex-{{ version }}.tar.gz
  sha256: de27bbf11b135a9cc7b03fc35f586705e286d6cd4fbbe112eaa577ed1c82a69f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - js_regex

about:
  home: https://github.com/Zac-HD/js-regex
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: "A thin compatibility layer to use Javascript regular expressions in Python"

extra:
  recipe-maintainers:
    - ocefpaf
